export enum Errors {
  EMAIL_EXIST = 'Email already exists, try another one',
  USERNAME_EXIST = 'Username already exists, try another one',
  NAME = 'Name already exists, try another one',
  DATA_NOT_FOUND = 'Data not found',
  FILE_NOT_FOUND = 'File not found',
  RANGE_SHOULD_BE_HEADER = 'range should be in header',
  FILE_STATS_ERROR = 'Error found reading file stats',
  REGISTRED_LICENSE_NOT_FOUND = 'This device has not been registered.',
  REGISTRED_LICENSE_EXPIRED = 'License has been expired.',
  USER_NOT_EXIST = "User doesn't exists!",
  USERNAME_OR_EMAIL_REQUIRED = 'Email and user name required',
  PASSWORD_DOES_NOT_MATCH = "Password doesn't match",
  TIER_NOT_FOUND = 'Tier not found',
  END_DATE_ERROR = 'End date should be greater then today date.',
  PRODUCT_NOT_FOUND = 'Product not found',
  LICENSE_NOT_ENOUGH = 'License is not enough to assign please generate more license to activate.',
  LICENSE_COUNT = 'Issued license is less then you enter amount',
  DEVICE_NUMBER = 'Device number already exists',
  LICENSED_NOT_FOUND = 'License not found',
  INTERNAL_SERVER_ERROR = 'Internal server error',
  LICENSE_ALREADY_ACTIVATED = 'License already activated on this device number',
  LICENSE_NUMBER_ALREADY_ACTIVATED = 'License already activated on this license number',
}
